name: TKT-CYBER-XMD-V3
services:
  - name: TKT-CYBER-XMD-V3-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
